import { Crop, DiagnosticResult, AlertItem, FarmerProfile, Language, FertilizerTask } from './types';

export const INITIAL_PROFILE: FarmerProfile = {
  name: 'Farmer Ramesh',
  location: 'Valley View Estate, Karnataka',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
  totalScans: 42,
  activeCropsCount: 12,
  avgHealthScore: 94,
  farmSizeAcres: 5.5,
  primaryCrops: ['Roma Tomato', 'Winter Wheat', 'Soybean'],
  notificationsOn: true,
  darkMode: false,
  language: 'English',
  phone: '+1 (555) 019-2834',
  email: 'ramesh.farmer@agrivision.ai',
  soilType: 'Red Loam Soil',
  isLoggedIn: false,
};

export const INITIAL_CROPS: Crop[] = [
  {
    id: 'crop-1',
    name: 'Roma Tomato',
    location: 'Block A, Row 4',
    healthScore: 87,
    lastScanned: 'Scanned 2h ago',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD9rIr1Yj87MpQWw3pu-rSGVlwidwrc_NqR3CJo-9VFxvQ6ySWe1KECFHmdgirBvyvAyK1hnVixkDLs4KEQlA8IXBULEcorxKFY-xsFFPJMMgmHJYkb64b3Iu34T69BjiahUF2kk09N5SDwvZWIDksbs7eII3BiA7pfYT2JYPJbOGpRuZSSAKsVxVXmrrzVdoX1gGLCAL7PPAA7bnJWG1O7MXeTGqrH1GAD7TYT520aIPwy-CwYlwNt',
    status: 'Healthy',
    plantedDaysAgo: 42,
    leafHealth: 92,
    weatherRisk: 20,
    diseaseRisk: 10,
    healthTrend: [60, 75, 52, 78, 87],
  },
  {
    id: 'crop-2',
    name: 'Winter Wheat',
    location: 'Field North-East',
    healthScore: 76,
    lastScanned: 'Scanned 1d ago',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBlnspucrFS-Pxx8j9s3jvXfVwwkpx47AfjhWedUFJ5Orv6B9asvVhjz1BJT5YPcZkydANvIB6NoPh26rX3dbuCoUa11yWMZgh5AyrtFFxomA9GMu6fp78BRfjyermt_Y0u0uXiUcWkMPdc2hyoNMWGJJZL-dgzN1a6GoMICawzmnIO-On_AWl1aOCwU8rPmML17rHpB_mxamBuGaxHEFN-i90G7e9IsKm12cw9fLHT1mJRy4kR1oHi',
    status: 'Warning',
    plantedDaysAgo: 60,
    leafHealth: 74,
    weatherRisk: 45,
    diseaseRisk: 30,
    healthTrend: [88, 85, 78, 72, 76],
  },
  {
    id: 'crop-3',
    name: 'Soybean',
    location: 'Sector B',
    healthScore: 92,
    lastScanned: 'Scanned 4h ago',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBCRaHr6QGHM78qhTdUWmmf0dgGK3K2VqeoMafqJ1bx9P8RV7MHp3_kJwbD5rbK3ZWEnItRt-iiFVMDn3ZHugY0ww0LP_9B63mRWZrF9BGLw7qhioodqlDCINl-6W_KGFSZ0hoRhRFjvaTgHw09wcm13kj381766WlRP1zvu_hxfej9SLnqekseutcbdin5DmUeIRNe_V_iFchUGExfS_v8lIbICCxBmVRIwbTPS42egSnZ2EP_Mx6n',
    status: 'Healthy',
    plantedDaysAgo: 30,
    leafHealth: 95,
    weatherRisk: 15,
    diseaseRisk: 8,
    healthTrend: [80, 84, 88, 90, 92],
  },
  {
    id: 'crop-4',
    name: 'Heirloom Tomato',
    location: 'Block A, Row 1',
    healthScore: 98,
    lastScanned: 'Scanned 20m ago',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDPlDF4aVcD8DfoxHK1icwrS5sS00BV-xd6ZjHAAK1Zs1bMWG5FklcJIaXIHBAOFDMe5HIloARrKraMiFxx8wJoP_dMCkXyp02w0y7onlxPyLEZayiAOm9azRBC_Qy2d1Qh542VH2TkWhb_EU7Y3x1-DKjMDfU0MJoQmwBI4zBQ5UwP7ybeFJ_-Ovx-f6G4XrvP43Xxc2zAC9Wj8aMVPxdaqB24wLRHT7PARr5iJoLcKcfZumDk9TtP',
    status: 'Healthy',
    plantedDaysAgo: 45,
    leafHealth: 98,
    weatherRisk: 10,
    diseaseRisk: 2,
    healthTrend: [90, 92, 94, 96, 98],
  },
];

export const DEFAULT_DIAGNOSIS_RESULT: DiagnosticResult = {
  cropName: 'Tomato Leaf',
  scanTime: '10:42 AM Today',
  disease: 'Early Blight',
  scientificName: 'Alternaria solani',
  confidence: 94,
  severity: 'Moderate',
  plantVitality: 62,
  symptoms: [
    {
      title: 'Concentric brown lesions',
      description: 'Primary indicator on lower leaves with dark target-like rings.',
      type: 'error',
    },
    {
      title: 'Chlorosis (Yellowing)',
      description: 'Surrounding yellow halo around lesion spots on leaves.',
      type: 'warning',
    },
  ],
  actionPlan: [
    {
      step: 1,
      title: 'Prune infected lower leaves',
      description: 'Carefully remove and destroy leaves showing lesions to prevent upward spread. Do not compost.',
    },
    {
      step: 2,
      title: 'Improve air circulation',
      description: 'Stake or cage plants and ensure adequate spacing. Avoid overhead watering.',
    },
    {
      step: 3,
      title: 'Apply targeted fungicide',
      description: 'Use a copper-based or chlorothalonil fungicide following manufacturer instructions for moderate severity.',
    },
  ],
  image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDPlDF4aVcD8DfoxHK1icwrS5sS00BV-xd6ZjHAAK1Zs1bMWG5FklcJIaXIHBAOFDMe5HIloARrKraMiFxx8wJoP_dMCkXyp02w0y7onlxPyLEZayiAOm9azRBC_Qy2d1Qh542VH2TkWhb_EU7Y3x1-DKjMDfU0MJoQmwBI4zBQ5UwP7ybeFJ_-Ovx-f6G4XrvP43Xxc2zAC9Wj8aMVPxdaqB24wLRHT7PARr5iJoLcKcfZumDk9TtP',
  summary: 'Analysis complete. Early Blight detected with moderate severity.',
};

export const INITIAL_ALERTS: AlertItem[] = [
  {
    id: 'alert-1',
    category: 'WEATHER RISK',
    title: 'High humidity alert in Block C',
    description: 'Elevated moisture levels detected. 85% risk of early fungal blight. Recommended: adjust irrigation schedule.',
    type: 'weather',
    time: '10:42 AM',
    dateGroup: 'Today',
    severity: 'critical',
    actionable: true,
  },
  {
    id: 'alert-2',
    category: 'AI ANALYSIS',
    title: 'Soybean growth trending up',
    description: 'Recent satellite imagery confirms a 12% increase in biomass compared to historical averages for this week.',
    type: 'ai',
    time: '08:15 AM',
    dateGroup: 'Today',
    severity: 'normal',
  },
  {
    id: 'alert-3',
    category: 'FIELD TASK',
    title: 'Check Block A Tomato health',
    description: 'Task marked as complete by field agent Marcus.',
    type: 'task',
    time: '06:00 AM',
    dateGroup: 'Today',
    completed: true,
  },
  {
    id: 'alert-4',
    category: 'SYSTEM UPDATE',
    title: 'New language pack available',
    description: 'Kannada and Marathi localizations are now active for field workers. Enable them in settings.',
    type: 'system',
    time: 'Yesterday',
    dateGroup: 'Earlier',
  },
  {
    id: 'alert-5',
    category: 'LOGISTICS',
    title: 'Fertilizer delivery scheduled',
    description: 'Expected arrival between 2PM - 4PM at the main depot.',
    type: 'logistics',
    time: 'Oct 12',
    dateGroup: 'Earlier',
  },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  English: {
    today: 'Today',
    greeting: 'Good Morning, Farmer 👋',
    cropTipTitle: "Today's Crop Tip:",
    cropTipText: 'High humidity may increase fungal disease risk. Check your tomato leaves.',
    isCropHealthy: 'Is your crop healthy?',
    takePhotoSub: 'Take a photo and let AI check it instantly.',
    scanCropNow: 'Scan Crop Now',
    scanDisease: 'Scan Disease',
    myCrops: 'My Crops',
    askAi: 'Ask AI',
    cropHealth: 'Crop Health',
    home: 'Home',
    crops: 'Crops',
    ai: 'AI',
    me: 'Me',
    alerts: 'Alerts',
    farmOverview: 'Farm Overview',
    total: 'TOTAL',
    avgHealth: 'AVG HEALTH',
    activeCrops: 'Active Crops',
    chooseLanguage: 'Choose Your Language',
    languageSub: 'Select your preferred language for advice and app interface.',
    continue: 'Continue',
  },
  Kannada: {
    today: 'ಇಂದು',
    greeting: 'ಶುಭೋದಯ, ರೈತರೇ 👋',
    cropTipTitle: 'ಇಂದಿನ ಬೆಳೆ ಸಲಹೆ:',
    cropTipText: 'ಹೆಚ್ಚಿನ ತೇವಾಂಶವು ಶಿಲೀಂಧ್ರ ರೋಗದ ಅಪಾಯವನ್ನು ಹೆಚ್ಚಿಸಬಹುದು. ನಿಮ್ಮ ಟೊಮೆಟೊ ಎಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    isCropHealthy: 'ನಿಮ್ಮ ಬೆಳೆ ಆರೋಗ್ಯವಾಗಿದೆಯೇ?',
    takePhotoSub: 'ಫೋಟೋ ತೆಗೆಯಿರಿ ಮತ್ತು AI ತಕ್ಷಣವೇ ಪರಿಶೀಲಿಸಲಿ.',
    scanCropNow: 'ಈಗ ಬೆಳೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    scanDisease: 'ರೋಗ ಸ್ಕ್ಯಾನ್',
    myCrops: 'ನನ್ನ ಬೆಳೆಗಳು',
    askAi: 'AI ಕೇಳಿ',
    cropHealth: 'ಬೆಳೆ ಆರೋಗ್ಯ',
    home: 'ಮುಖ್ಯ ಪುಟ',
    crops: 'ಬೆಳೆಗಳು',
    ai: 'AI ಸಲಹೆಗಾರ',
    me: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    alerts: 'ಎಚ್ಚರಿಕೆಗಳು',
    farmOverview: 'ಫಾರ್ಮ್ ಅವಲೋಕನ',
    total: 'ಒಟ್ಟು',
    avgHealth: 'ಸರಾಸರಿ ಆರೋಗ್ಯ',
    activeCrops: 'ಸಕ್ರಿಯ ಬೆಳೆಗಳು',
    chooseLanguage: 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    languageSub: 'ಸಲಹೆ ಮತ್ತು ಅಪ್ಲಿಕೇಶನ್ ಇಂಟರ್ಫೇಸ್‌ಗಾಗಿ ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    continue: 'ಮುಂದುವರಿಸಿ',
  },
  Hindi: {
    today: 'आज',
    greeting: 'शुभ प्रभात, किसान भाई 👋',
    cropTipTitle: 'आज की फसल टिप:',
    cropTipText: 'उच्च आर्द्रता से कवक रोग का खतरा बढ़ सकता है। अपने टमाटर के पत्तों की जाँच करें।',
    isCropHealthy: 'क्या आपकी फसल स्वस्थ है?',
    takePhotoSub: 'फोटो लें और AI को तुरंत जांच करने दें।',
    scanCropNow: 'अभी फसल स्कैन करें',
    scanDisease: 'बीमारी स्कैन करें',
    myCrops: 'मेरी फसलें',
    askAi: 'AI से पूछें',
    cropHealth: 'फसल स्वास्थ्य',
    home: 'होम',
    crops: 'फसलें',
    ai: 'AI सहायक',
    me: 'प्रोफ़ाइल',
    alerts: 'अलर्ट',
    farmOverview: 'फार्म अवलोकन',
    total: 'कुल',
    avgHealth: 'औसत स्वास्थ्य',
    activeCrops: 'सक्रिय फसलें',
    chooseLanguage: 'अपनी भाषा चुनें',
    languageSub: 'सलाह और ऐप इंटरफ़ेस के लिए अपनी पसंदीदा भाषा चुनें।',
    continue: 'जारी रखें',
  },
  Telugu: {
    today: 'ఈ రోజు',
    greeting: 'శుభోదయం, రైతు సోదరా 👋',
    cropTipTitle: 'ఈనాటి పంట చిట్కా:',
    cropTipText: 'అధిక తేమ వల్ల శిలీంధ్ర వ్యాధి ముప్పు పెరుగుతుంది. మీ టమాటా ఆకులను తనిఖీ చేయండి.',
    isCropHealthy: 'మీ పంట ఆరోగ్యంగా ఉందా?',
    takePhotoSub: 'ఫోటో తీయండి, AI తక్షణమే తనిఖీ చేస్తుంది.',
    scanCropNow: 'ఇప్పుడే స్కాన్ చేయండి',
    scanDisease: 'వ్యాధి స్కాన్',
    myCrops: 'నా పంటలు',
    askAi: 'AI ని అడగండి',
    cropHealth: 'పంట ఆరోగ్యం',
    home: 'హోమ్',
    crops: 'పంటలు',
    ai: 'AI అసిస్టెంట్',
    me: 'ప్రొఫైల్',
    alerts: 'అలర్ట్లు',
    farmOverview: 'ఫామ్ వివరాలు',
    total: 'మొత్తం',
    avgHealth: 'సగటు ఆరోగ్యం',
    activeCrops: 'యాక్టివ్ పంటలు',
    chooseLanguage: 'మీ భాషను ఎంచుకోండి',
    languageSub: 'సలహాలు మరియు యాప్ ఇంటర్‌ఫేస్ కోసం మీ ప్రాధాన్యత భాషను ఎంచుకోండి.',
    continue: 'కొనసాగించండి',
  },
  Tamil: {
    today: 'இன்று',
    greeting: 'காலை வணக்கம், உழவரே 👋',
    cropTipTitle: 'இன்றைய பயிர் குறிப்பு:',
    cropTipText: 'அதிக ஈரப்பதம் பூஞ்சை நோய் ஆபத்தை அதிகரிக்கும். உங்கள் தக்காளி இலைகளை சரிபார்க்கவும்.',
    isCropHealthy: 'உங்கள் பயிர் ஆரோக்கியமாக உள்ளதா?',
    takePhotoSub: 'படம் எடுத்து AI உடனடியாக சோதிக்க அனுமதிக்கவும்.',
    scanCropNow: 'இப்போதே ஸ்கேன் செய்',
    scanDisease: 'நோய் ஸ்கேன்',
    myCrops: 'என் பயிர்கள்',
    askAi: 'AI இடம் கேள்',
    cropHealth: 'பயிர் ஆரோக்கியம்',
    home: 'முகப்பு',
    crops: 'பயிர்கள்',
    ai: 'AI உதவி',
    me: 'சுயவிவரம்',
    alerts: 'எச்சரிக்கைகள்',
    farmOverview: 'பண்ணை மேலோட்டம்',
    total: 'மொத்தம்',
    avgHealth: 'சராசரி ஆரோக்கியம்',
    activeCrops: 'செயலில் உள்ள பயிர்கள்',
    chooseLanguage: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    languageSub: 'ஆலோசனை மற்றும் பயன்பாட்டு இடைமுகத்திற்கு உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்.',
    continue: 'தொடரவும்',
  },
  Marathi: {
    today: 'आज',
    greeting: 'शुभ प्रभात, शेतकरी दादा 👋',
    cropTipTitle: 'आजची पीक टीप:',
    cropTipText: 'जास्त आर्द्रतेमुळे बुरशीजन्य रोगाचा धोका वाढू शकतो. आपल्या टोमॅटोच्या पानांची तपासणी करा.',
    isCropHealthy: 'तुमचे पीक निरोगी आहे का?',
    takePhotoSub: 'फोटो काढा आणि AI ला त्वरित तपासू द्या.',
    scanCropNow: 'आत्ताच पीक स्कॅन करा',
    scanDisease: 'रोग स्कॅन करा',
    myCrops: 'माझी पिके',
    askAi: 'AI ला विचारा',
    cropHealth: 'पीक आरोग्य',
    home: 'मुख्य',
    crops: 'पिके',
    ai: 'AI सहाय्यक',
    me: 'प्रोफाइल',
    alerts: 'अलर्ट',
    farmOverview: 'शेताचा आढावा',
    total: 'एकूण',
    avgHealth: 'सरासरी आरोग्य',
    activeCrops: 'सक्रिय पिके',
    chooseLanguage: 'तुमची भाषा निवडा',
    languageSub: 'सल्ला आणि ॲप इंटरफेससाठी तुमची आवडती भाषा निवडा.',
    continue: 'पुढे जा',
  },
};

export const INITIAL_FERTILIZER_TASKS: FertilizerTask[] = [
  {
    id: 'ftask-1',
    cropId: 'crop-1',
    cropName: 'Roma Tomato',
    growthStage: 'Flowering',
    fertilizerName: 'NPK 19-19-19 + Micronutrients',
    dosage: '5 kg / acre',
    applicationMethod: 'Drip Fertigation',
    dueDate: 'Today',
    daysFromPlanting: 42,
    completed: false,
    notes: 'Boosts flower cluster development and prevents early blossom drop.',
  },
  {
    id: 'ftask-2',
    cropId: 'crop-1',
    cropName: 'Roma Tomato',
    growthStage: 'Fruiting',
    fertilizerName: 'Calcium Nitrate + Boron Spray',
    dosage: '300 g / 100L water',
    applicationMethod: 'Foliar Spray',
    dueDate: 'In 6 days',
    daysFromPlanting: 48,
    completed: false,
    notes: 'Essential to prevent Blossom End Rot during early fruit setting.',
  },
  {
    id: 'ftask-3',
    cropId: 'crop-2',
    cropName: 'Winter Wheat',
    growthStage: 'Vegetative',
    fertilizerName: 'Top-dressing Urea (46% Nitrogen)',
    dosage: '25 kg / acre',
    applicationMethod: 'Soil Drenching',
    dueDate: 'Tomorrow',
    daysFromPlanting: 60,
    completed: false,
    notes: 'Second split dose for maximum tillering and leaf canopy expansion.',
  },
  {
    id: 'ftask-4',
    cropId: 'crop-3',
    cropName: 'Soybean',
    growthStage: 'Vegetative',
    fertilizerName: 'Bio-Fertilizer (Rhizobium + PSB)',
    dosage: '10 kg / acre',
    applicationMethod: 'Basal Application',
    dueDate: 'In 3 days',
    daysFromPlanting: 30,
    completed: false,
    notes: 'Promotes root nodulation and natural nitrogen fixation.',
  },
];

export const STAGE_FERTILIZER_GUIDE = [
  {
    stage: 'Germination',
    daysRange: '0 - 14 Days',
    recommended: 'Single Super Phosphate (SSP) + Neem Cake',
    purpose: 'Deep root anchorage and soil conditioning',
    method: 'Basal Application',
    icon: 'sprout',
  },
  {
    stage: 'Vegetative',
    daysRange: '15 - 35 Days',
    recommended: 'Urea (46% N) + NPK 20-20-20',
    purpose: 'Vigorous leaf growth & photosynthetic canopy',
    method: 'Soil Drenching / Fertigation',
    icon: 'eco',
  },
  {
    stage: 'Flowering',
    daysRange: '36 - 55 Days',
    recommended: 'NPK 19-19-19 + Boron 20%',
    purpose: 'Enhance flower formation and pollen fertility',
    method: 'Drip Fertigation / Foliar Spray',
    icon: 'local_florist',
  },
  {
    stage: 'Fruiting',
    daysRange: '56 - 80 Days',
    recommended: 'Calcium Nitrate + Sulphate of Potash (0-0-50)',
    purpose: 'Fruit firmness, sugar density, and rot prevention',
    method: 'Foliar Spray',
    icon: 'nutrition',
  },
  {
    stage: 'Maturation',
    daysRange: '81+ Days',
    recommended: 'Micronutrient Foliar Spray (Zn, Fe, Mg)',
    purpose: 'Pre-harvest grain/fruit weight and uniform ripening',
    method: 'Light Foliar Spray',
    icon: 'potted_plant',
  },
];

export const MOCK_CROPS = INITIAL_CROPS;
export const MOCK_ALERTS = INITIAL_ALERTS;
export const DEFAULT_DIAGNOSIS = DEFAULT_DIAGNOSIS_RESULT;

